spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bank
    driverClassName: org.postgresql.Driver

liquibase:
  changelog:
    location: classpath:/database/changelog-master.xml
  schema: bank

registration:
  startBalance: 100
  defaultUsers:
    - username: 1
      password: asd
      balance: 100
    - username: 2
      password: asd
      balance: 100