registration:
  startBalance: 100
  defaultUsers:
    - username: 1
      password: asd
      balance: 100
    - username: 2
      password: asd
      balance: 100
database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/bank
  username: postgres
  password: postgres